### ISSUE TITLE
Score MOCs

### ISSUE THREAD

**Issue by aronwc** [casmlab/purpletag#9]
- Add a new output to the `score` command to list polarization scores for each member of congress.

**Comment by libbyh** [comment]
I think c31c568465c780de06d7031684b5fa0e1feef69c fixes this, but can you take a look before I push to master?

**Comment by aronwc** [comment]
Looks good to me. At some point we should write some tests, but that can
wait.

**Comment by libbyh** [comment]
Can I close this, or should I leave it open until we write some tests?

**Comment by aronwc** [comment]
Closing!
